batch_size: 128
classifier_type: nn
epochs: 10
hidden_dim: 32
learning_rate: 0.01
log_batches: 10
mode: snapshot
seed: 239
test_size: 0.1
skip_read_write: 0
final_test: 1
training_method : original  #GradAug,original

source_folder:  E:/NLP/RoPGen/src/authorship-detection-master_PbNN/attribution/processed/gcj_java/java/



